apiVersion: apps/v1
kind: Deployment
metadata:
  name: volvo-dmc-deployment
  labels:
    app: volvo-dmc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volvo-dmc
  template:
    metadata:
      labels:
        app: volvo-dmc
    spec:
      containers:
      - name: volvo-dmc-container
        image: volvo_dmc:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: volvo-dmc-service
spec:
  selector:
    app: volvo-dmc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
