# Railway.app deployment configuration
# This file tells Railway how to deploy your VOLVO DMC Generator

[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "cd deploy && gunicorn --bind 0.0.0.0:$PORT --workers 2 main:app"
  healthcheckPath = "/"
  restartPolicyType = "ON_FAILURE"

[env]
  PORT = "8000"
  FLASK_ENV = "production"
  PYTHONPATH = "/app/backend:/app"
