# Azure App Service deployment configuration with Docker
name: Deploy to Azure Web App (Docker)

on:
  # Temporarily disabled for testing
  # push:
  #   branches: [ main ]
  workflow_dispatch: # Only run manually

env:
  AZURE_WEBAPP_NAME: volvo-dmc-generator
  DOCKER_IMAGE_NAME: volvo-dmc-generator
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/volvo-dmc-generator
  AZURE_RESOURCE_GROUP: rg-volvo-dmc-generator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest python test_dependencies.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Only run deployment if Azure secrets are configured
    if: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE != '' }}
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: 'Deploy Docker container to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE == '' }}
    
    steps:
    - name: Notify about missing Azure configuration
      run: |
        echo "🔧 Azure deployment skipped - missing configuration"
        echo "📋 To enable Azure deployment:"
        echo "1. Create Azure Web App with Container support"
        echo "2. Add AZUREAPPSERVICE_PUBLISHPROFILE to GitHub Secrets"
        echo "3. Configure the Web App to use Container Registry"
        echo "4. Re-run this workflow"
        echo ""
        echo "📖 Docker image will be available at:"
        echo "   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo ""
        echo "🐳 To run locally:"
        echo "   docker run -p 8000:8000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
