name: Build and Push to Nawoar ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: nawoar.azurecr.io
  IMAGE_NAME: volvo-dmc
  RESOURCE_GROUP: MDC
  CONTAINER_APP_NAME: volvo-dmc-generator

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Log in to Azure Container Registry
      run: az acr login --name nawoar
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Update Container App (optional)
      run: |
        echo "🎉 Image built and pushed successfully!"
        echo "🌐 Registry: ${{ env.REGISTRY }}"
        echo "📦 Image: ${{ env.IMAGE_NAME }}:latest"
        echo ""
        echo "✅ Update your Azure Container App with:"
        echo "   Registry: ${{ env.REGISTRY }}"
        echo "   Image: ${{ env.IMAGE_NAME }}"
        echo "   Tag: latest"
      
    - name: 🔐 Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: ⚙️ Setup Azure Developer CLI
      uses: Azure/setup-azd@v0.1.0
      
    - name: 🏗️ Run azd provision
      run: azd provision --no-prompt
      env:
        AZURE_ENV_NAME: volvo-dmc-prod
        AZURE_LOCATION: eastus
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: 🚀 Run azd deploy
      run: azd deploy --no-prompt
      env:
        AZURE_ENV_NAME: volvo-dmc-prod
        AZURE_LOCATION: eastus
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
