# Azure App Service deployment configuration
name: Deploy to Azure Web App

on:
  # Temporarily disabled for testing
  # push:
  #   branches: [ main ]
  workflow_dispatch: # Only run manually

env:
  AZURE_WEBAPP_NAME: volvo-dmc-generator
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdmtx0b libdmtx-dev

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements-minimal.txt

    - name: Test dependencies
      run: |
        source venv/bin/activate
        python test_dependencies.py

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          .
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Only run deployment if Azure secrets are configured
    if: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE != '' }}
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE == '' }}
    
    steps:
    - name: Notify about missing Azure configuration
      run: |
        echo "🔧 Azure deployment skipped - missing configuration"
        echo "📋 To enable Azure deployment:"
        echo "1. Create Azure Web App"
        echo "2. Add AZUREAPPSERVICE_PUBLISHPROFILE to GitHub Secrets"
        echo "3. Re-run this workflow"
        echo ""
        echo "📖 See AZURE_DEPLOYMENT.md for detailed instructions"
