name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzbar0 libzbar-dev libgl1-mesa-glx
          python -m pip install --upgrade pip
          pip install -r deploy/requirements.txt
      
      - name: Build static site
        run: |
          mkdir -p _site
          cp -r backend/templates/* _site/
          cp -r backend/static/* _site/
          # Create index.html for GitHub Pages
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>VOLVO DMC Generator</title>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <link rel="stylesheet" href="style.css">
          </head>
          <body>
              <div class="container">
                  <h1>🚀 VOLVO DMC Generator</h1>
                  <p>Your VOLVO DMC Generator is ready!</p>
                  
                  <div class="deployment-options">
                      <h2>Choose Your Deployment:</h2>
                      
                      <div class="option">
                          <h3>🎯 GitHub Codespaces (Recommended)</h3>
                          <p>Run your app directly in GitHub:</p>
                          <ol>
                              <li>Go to your GitHub repository</li>
                              <li>Click "Code" → "Codespaces" → "Create codespace"</li>
                              <li>Run: <code>cd deploy && python main.py</code></li>
                              <li>Your app will be live in the codespace!</li>
                          </ol>
                          <a href="https://github.com/GOD-FATHEl2/volvo-dmc-generator" class="btn">Open Repository</a>
                      </div>
                      
                      <div class="option">
                          <h3>⚡ Railway (1-Click Deploy)</h3>
                          <p>Deploy directly from GitHub:</p>
                          <a href="https://railway.app/template/github.com/GOD-FATHEl2/volvo-dmc-generator" class="btn">Deploy to Railway</a>
                      </div>
                      
                      <div class="option">
                          <h3>🔥 Render (Free Hosting)</h3>
                          <p>Free hosting with GitHub integration:</p>
                          <a href="https://render.com/deploy?repo=https://github.com/GOD-FATHEl2/volvo-dmc-generator" class="btn">Deploy to Render</a>
                      </div>
                  </div>
              </div>
              
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                      line-height: 1.6;
                      margin: 0;
                      padding: 20px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      min-height: 100vh;
                  }
                  .container {
                      max-width: 800px;
                      margin: 0 auto;
                      background: rgba(255, 255, 255, 0.1);
                      padding: 30px;
                      border-radius: 15px;
                      backdrop-filter: blur(10px);
                  }
                  h1 {
                      text-align: center;
                      font-size: 2.5em;
                      margin-bottom: 10px;
                  }
                  .option {
                      background: rgba(255, 255, 255, 0.1);
                      padding: 20px;
                      margin: 20px 0;
                      border-radius: 10px;
                      border-left: 4px solid #00ff88;
                  }
                  .btn {
                      display: inline-block;
                      background: #00ff88;
                      color: #000;
                      padding: 12px 24px;
                      text-decoration: none;
                      border-radius: 5px;
                      font-weight: bold;
                      margin: 10px 10px 10px 0;
                      transition: transform 0.2s;
                  }
                  .btn:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 5px 15px rgba(0, 255, 136, 0.3);
                  }
                  code {
                      background: rgba(0, 0, 0, 0.3);
                      padding: 2px 6px;
                      border-radius: 3px;
                      font-family: 'Courier New', monospace;
                  }
              </style>
          </body>
          </html>
          EOF
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
