name: Deploy to GitHub Pages

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdmtx0b libdmtx-dev libzbar0 libzbar-dev
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-minimal.txt
          
      - name: Test application
        run: |
          cd backend
          python -c "print('✅ Python environment ready')"
          python -c "import Flask; print('✅ Flask available')"
          python test_dependencies.py
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create static site
        run: |
          mkdir -p _site
          cp -r frontend/* _site/
          cp -r backend/static/* _site/ 2>/dev/null || true
          echo "# Volvo DMC Generator" > _site/README.md
          echo "This is the frontend of the Volvo DMC Generator application." >> _site/README.md
          echo "The backend requires a server to run properly." >> _site/README.md
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
